### ISSUE TITLE
Docker auto exit with command "docker run -it onnxim", how should I debug further?

### ISSUE THREAD

**Issue by qshan** [PSAL-POSTECH/ONNXim#10]
hi, I hit this issue from my side, Here is docker inspect info:
$docker inspect 6a3f6620a250
[
    {
        "Id": "6a3f6620a25041e7c17a75ab8203890c3a53ee39463ff2bd840a18295bc217a6",
        "Created": "2024-08-19T08:32:06.980871424Z",
        "Path": "echo",
        "Args": [
            "Welcome to ONNXim!"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-08-19T08:32:07.290059127Z",
            "FinishedAt": "2024-08-19T08:32:07.293156272Z"
        },
        "Image": "sha256:9618c72aa7f0202b9a2694ee2f2c78ed4c92bab55788aa41918e911de6d11478",
        "ResolvConfPath": "/var/lib/docker/containers/6a3f6620a25041e7c17a75ab8203890c3a53ee39463ff2bd840a18295bc217a6/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6a3f6620a25041e7c17a75ab8203890c3a53ee39463ff2bd840a18295bc217a6/hostname",
        "HostsPath": "/var/lib/docker/containers/6a3f6620a25041e7c17a75ab8203890c3a53ee39463ff2bd840a18295bc217a6/hosts",
        "LogPath": "/var/lib/docker/containers/6a3f6620a25041e7c17a75ab8203890c3a53ee39463ff2bd840a18295bc217a6/6a3f6620a25041e7c17a75ab8203890c3a53ee39463ff2bd840a18295bc217a6-json.log",
        "Name": "/confident_lederberg",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                36,
                126
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteIOps": [],
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": [],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/412447ddc1f84ec0e569ce632fc0b3acc284a20751d9307e6666989b85790f78-init/diff:/var/lib/docker/overlay2/b258lqx4fl2feqyxav0fw93nk/diff:/var/lib/docker/overlay2/rjaiv9i79fi3ypn1epd9da6va/diff:/var/lib/docker/overlay2/9mrynobruj04pjmfy7ao1zjjk/diff:/var/lib/docker/overlay2/3ys11ghdjj76f2arqbl2t8gm4/diff:/var/lib/docker/overlay2/scgfi26pu2ieq569jfcqaywgk/diff:/var/lib/docker/overlay2/j62ucpbfnocij0gbl3m3igtkq/diff:/var/lib/docker/overlay2/o4j8eyj79xcuo12gbmbadn8l0/diff:/var/lib/docker/overlay2/03b933a63f14f36f8048e0f02359f1689ac4b032e7e793c4de243355945faa50/diff",
                "MergedDir": "/var/lib/docker/overlay2/412447ddc1f84ec0e569ce632fc0b3acc284a20751d9307e6666989b85790f78/merged",
                "UpperDir": "/var/lib/docker/overlay2/412447ddc1f84ec0e569ce632fc0b3acc284a20751d9307e6666989b85790f78/diff",
                "WorkDir": "/var/lib/docker/overlay2/412447ddc1f84ec0e569ce632fc0b3acc284a20751d9307e6666989b85790f78/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "6a3f6620a250",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ONNXIM_HOME=/workspace/ONNXim"
            ],
            "Cmd": [
                "echo",
                "Welcome to ONNXim!"
            ],
            "Image": "onnxim",
            "Volumes": null,
            "WorkingDir": "/workspace",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.version": "20.04"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "4d820b8c658d0c904e058e550f063ced3f081ed5dc2dcfc0162c9df7f247ac5e",
            "SandboxKey": "/var/run/docker/netns/4d820b8c658d",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "",
                    "NetworkID": "2ea3c122023c2272d368ce1d1d9a3e600e035820fad47ee92c6920989b7399ae",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": null
                }
            }
        }
    }
]

**Comment by YWHyuk** [comment]
try this
`docker run -it onnxim /bin/bash`

**Comment by qshan** [comment]
hi, @YWHyuk 
   Worked from my side with your comments. Thanks so much!
