### ISSUE TITLE
Questions about the paper & repo

### ISSUE THREAD

**Issue by linbaiwpi** [PSAL-POSTECH/ONNXim#13]
Hi there,
Thanks for providing such a great paper and code. I have read your paper in arXiv, but still have some questions. Could you explain it a little bit for me?

About the article:
1) How did you compare the prediction accuracy to chips like Eyeriss and TPU? I believe the source code of them are not available in public.
2) How did you consider the data orchestration and memory bank conflict?
3) Does ONNXim target to systolic array (WS/IS/OS) only?

About the code:
4) Is there optimizer for optimal mapping? If yes, could you let me know where it is in code?
5) It is mentioned in II-A, "the tile size are chosen using heuristics form prior work [8]". So the tile size calculator in ONNXim is exactly to the one from Gemmini?
6) How did you calculate the data manipulation time (e.g. from global buffer to local buffer)?

**Comment by HamHyungkyu** [comment]
Hi, thank you for your interest in our work.

Here are the responses to your questions:

1) We compared the prediction accuracy to GEMMINI RTL models, which are publicly available. 
2) In this work, we targeted regular-patterned computations with deterministic latency, assuming that bank conflicts do not occur. However, supporting more complex computations with potential bank conflicts could be an area for future improvements.
3) Initially, we targeted a systolic array-based structure, but it can be extended to other structures, such as adder-tree-based architectures.
4) You can use the Timeloop mapper for finding optimal mappings. ONNXim can load mapping information from a file, and it prioritizes that mapping when provided.
5) If no mapping is provided, we use the fallback heuristics from GEMMINI.  The relevant  code is implemented in https://github.com/PSAL-POSTECH/ONNXim/blob/master/src/Mapping.cc
6) The latency of data movement from the on-chip cache is included in the operation latency. For instance, the GEMM_PRELOAD operation includes preload latency from the scratchpad to buffers in the systolic array, as well as the computation time within the systolic array.

I hope this response helps. If you have further questions, feel free to ask.

**Comment by linbaiwpi** [comment]
Thanks for your answers. I'll close it since no more questions right now.
