### ISSUE TITLE
Functional test

### ISSUE THREAD

**Issue by Junhyuk** [PSAL-POSTECH/ONNXim#5]
is Functional test is included to checkout in/output result  ??

**Comment by YWHyuk** [comment]
Hi @Junhyuk.
Unfortunately, ONNXim does not support the functionality to calculate the exact output value for given inputs.

**Comment by Junhyuk** [comment]
@YWHyuk 

Thanks for your reply.
is there any compiler to optimize model execution time ??

**Comment by YWHyuk** [comment]
We use ONNX runtime's graph optimizer. 
This graph optimization include kernel fusion (e.g., CONV-BN) for CNN and Attention fusion for Transformer. 

For more information, follow this link ([link](https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html))
